name: hadish

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./configs:/usr/local/openresty/nginx/conf:ro
      - ./modules:/usr/local/openresty/nginx/modules:ro
      - ./tests:/usr/local/openresty/nginx/tests:ro
      - ./logs:/usr/local/openresty/nginx/logs

    develop:
      watch:
        - action: rebuild
          path: ./modules
        - action: rebuild
          path: ./tests
        - action: rebuild
          path: ./configs

    # restart: unless-stopped
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    driver: bridge
