name: hadish

services:
  api-gateway:
    image: openresty/openresty:1.21.4.1-6-alpine-fat
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./configs:/usr/local/openresty/nginx/conf:ro
      - ./modules:/usr/local/openresty/nginx/modules:ro
      - ./tests:/usr/local/openresty/nginx/tests:ro
      - ./logs:/usr/local/openresty/nginx/logs

    command: >
      sh -c "
             opm get thibaultcha/lua-resty-jit-uuid &&
             /usr/local/openresty/bin/openresty -g 'daemon off;'"

    restart: unless-stopped
    networks:
      - api-gateway-network

  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: api-gateway-test
    volumes:
      - ./configs:/usr/local/openresty/nginx/conf:ro
      - ./modules:/usr/local/openresty/nginx/modules:ro
      - ./tests:/usr/local/openresty/nginx/tests:ro
      - ./logs:/usr/local/openresty/nginx/logs
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    driver: bridge
